# Generated by Django 3.2.10 on 2022-03-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_productos_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='detalle',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
