# Generated by Django 3.2.10 on 2022-03-22 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_auto_20220322_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='estado',
            new_name='Estado',
        ),
    ]
