# Generated by Django 3.2.10 on 2022-03-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_rename_estado_productos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='detalle',
            field=models.CharField(default='', max_length=250),
        ),
    ]
