# Generated by Django 3.2.10 on 2022-03-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
